export default {
  defaultBG: require('@/assets/images/defaultBG.png'),
  deafultBGClipped: require('@/assets/images/defaultBGclipped.png'),
  disaster: require('@/assets/images/disaster.png'),
  favicon: require('@/assets/images/favicon.png'),
  homeBG: require('@/assets/images/HomeBG.png'),
  icon: require('@/assets/images/icon.png'),
  logo1: require('@/assets/images/Logo1.png'),
  logo2: require('@/assets/images/Logo2.png'),
  logo3: require('@/assets/images/Logo3.png'),
  mail: require('@/assets/images/mail.png'),
  partialReactLogo: require('@/assets/images/partial-react-logo.png'),
  predictions: require('@/assets/images/predictions.png'),
  profilePic: require('@/assets/images/profilePic.jpeg'),
  splash: require('@/assets/images/splash.png'),
  weatherIcon: require('@/assets/images/weather-icon.png'),
  weather: require('@/assets/images/weather.png'),
  FloodWarning: require('@/assets/images/uploads/warning.png'),
};
